### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [buddhaplex/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by buddhaplex** [comment]
Hey Marco,

Thanks for that. Added the code to the header, and things are looking great! One thing though, the CSS that forces the footer copy to align left on smaller screens doesn't seem to be working. Any chance you can see what may be happening by looking at the code? I went over the steps again and I executed exactly as it said. 
Thanks!
Eric

**Comment by MarcoMorawec** [comment]
@buddhaplex I'm not 100% what you're referring to. 

Keep in mind that Twitter Bootstrap will set a so called "gutter" of a few pixel on the left and right hand side, so content isn't flush against the side of the screen. That could be what trips you up. Other than that, I just took a look at your app on my iPhone and things look solid.
